#must load jags.data from CMR jags model and mcmc output
plot(jags.data$ice[-c(1,25)], out$mean$phiA)
df = data.frame(ice=jags.data$ice[-c(1,25)], phiA=out$mean$phiA)
fit <- gam(phiA~s(ice, bs="cr", k=5), family=gaussian, data=df)
ndf <- data.frame(ice=seq(-2.5, 3, length=100))
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit)

df <- data.frame(df, ice2=df$ice^2)
fit2 <- glm(phiA~ice+ice2, family=gaussian, data=df)
summary(fit2)
ndf <- data.frame(ndf, ice2=ndf$ice^2)
preds2 <- predict(fit2, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)

#What about p-splines?
fit <- gam(phiA~s(ice, bs="ps", m=c(2, 2), k=5), family=gaussian, data=df)
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)

#and B-splines with second derivative penalty?
fit <- gam(phiA~s(ice, bs="bs", m=c(3, 2), k=5), family=gaussian, data=df)
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)
#seems similar to above p-spline with m=c(2,2)
#all above seem similar, so use p-splines with m=c(2,2)

#what about tprs?
fit <- gam(phiA~s(ice, k=5), family=gaussian, data=df)
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)
#also very similar

#what about gaussian process?
fit <- gam(phiA~s(ice, k=5, bs="gp", m=c(3)), family=gaussian, data=df)
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)

#set up knot positions
knots = list(ice=c(-2.5, -2.2, seq(-1.9, 1.4, length=8), 2.2, 3))
fit <- gam(phiA~s(ice, bs="ps", m=c(2, 2), k=8), family=gaussian, data=df, knots=knots, outer.ok=TRUE)
preds <- predict(fit, newdata=ndf, type="response", se.fit=TRUE)
plot(ndf$ice, preds$fit, type="l", ylim=c(0.25, 1), lwd=2)
lines(ndf$ice, preds2$fit, lty=2, lwd=2)
points(df$ice, df$phiA)
lines(ndf$ice, preds$fit+preds$se.fit, lty=1)
lines(ndf$ice, preds$fit-preds$se.fit, lty=1)
lines(ndf$ice, preds2$fit+preds2$se.fit, lty=2)
lines(ndf$ice, preds2$fit-preds2$se.fit, lty=2)
